# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abastida <abastida@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/10 13:51:08 by abastida          #+#    #+#              #
#    Updated: 2022/11/11 12:25:35 by abastida         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	$(MAKE) -f client.mk
	$(MAKE) -f server.mk

clean:
	$(MAKE) -f client.mk clean
	$(MAKE) -f server.mk clean
fclean:
	$(MAKE) -f client.mk fclean
	$(MAKE) -f server.mk fclean
